### PR TITLE
Add a *very important* gif to the readme

### PR DESCRIPTION
**Pull request by kaldrenon**

### CODE REVIEW

**Comment by megalithic** [comment]
I didn't think github was smart enough to reason about rendering a normal link to an image properly (e.g. an img tag).

might i suggest the below, for super quick gif rendering in the README:

``` markdown
<img src="http://i.imgur.com/n5ebMxv.gif" />
```

**Comment by ernie** [comment]
:heart: but no. :)

**Comment by kaldrenon** [comment]
:stuck_out_tongue:

**Pull request closed without merging**
